Redux
yegorgangalo/tic-tac-toe pull request #1
Opened 2021-03-23 15:29 UTC by yegorgangalo

2021-03-24 06:05 UTC, EugeneSolovyev requested changes

2021-03-24 06:05 UTC, EugeneSolovyev commented on src/App.js
> +  useEffect(() => {
useEffect получился через чур длинным
так не должно быть
те функции которые у тебя содержаться внутри, лучше вынести за пределы useEffect

2021-03-24 06:05 UTC, EugeneSolovyev commented on src/components/Form/Form.js
> +    }
https://formik.org/
https://redux-form.com/8.3.0/

для формы используй что-то из этого

2021-03-24 06:05 UTC, EugeneSolovyev commented on src/components/PlayTable/PlayTable.js
> +              <PlayCell key={idx} id={idx} content={cellContent} handleTurn={handleTurn} />
использование второго параметра map (index) - плохая практика для использования в key
т.к. есть вероятность того что будут проблемы с ре-рендерингом

2021-03-24 06:05 UTC, EugeneSolovyev commented on src/components/TurnToPlay/TurnToPlay.js
> +                <span className={s.turnToPlay}>{currentPlayer.name} </span>
s переназови в styles

2021-03-24 06:05 UTC, EugeneSolovyev commented on src/index.js
> +      {/* <PersistGate loading={null} persistor={persistor}> */}
ненужный код удаляем
в т.ч. и импорты

2021-03-24 06:05 UTC, EugeneSolovyev commented on src/redux/playCells/playCells-reducer.js
> +const showCellsScreen = createReducer(false, {
напомни, я тебе покажу как можно всё это уместить в 5 строк кода

2021-03-25 09:02 UTC, yegorgangalo commented on src/components/PlayTable/PlayTable.js
> +              <PlayCell key={idx} id={idx} content={cellContent} handleTurn={handleTurn} />
Переделал через shortid

2021-03-25 11:48 UTC, yegorgangalo commented on src/index.js
> +      {/* <PersistGate loading={null} persistor={persistor}> */}
Он нужен. Просто забыл включить)

2021-03-25 11:52 UTC, yegorgangalo commented on src/components/Form/Form.js
> +    }
Раньше использовал https://formik.org/. Не нравится из-за кучи кода.
react-hook-form более лаконична.
За https://redux-form.com/8.3.0/ даже не слышал. 
На проектах принципиально нужно будет использовать formik либо redux-form. Или это дело вкуса?

2021-03-25 11:52 UTC, yegorgangalo commented on src/components/TurnToPlay/TurnToPlay.js
> +                <span className={s.turnToPlay}>{currentPlayer.name} </span>
Мне наоборот говорили называть кратко так, как и так понятно что это. Это принципиально?

2021-03-25 12:04 UTC, yegorgangalo commented on src/App.js
> +  useEffect(() => {
Если я вытягиваю все оглашения функций из useEffect, тогда реакт матюкается.
Вот как я делаю:
useEffect(() => {
    if (count < 5) {
      return;
    }

    if (isWinner(playCells)) {
      addPlusOneVictory();
      refreshPlayCells();
    }

    if (isAllCellsMarked()) {
      refreshPlayCells();
    }
  }, [count, playCells, isWinner, addPlusOneVictory, isAllCellsMarked, refreshPlayCells])
  
  И вот что говорит реакт:
  react_devtools_backend.js:2430 src/App.js
  Line 34:11:  The 'isWinner' function makes the dependencies of useEffect Hook (at line 73) change on every render. Move it inside the useEffect callback. Alternatively, wrap the definition of 'isWinner' in its own useCallback() Hook                    react-hooks/exhaustive-deps
  Line 44:9:   The 'isAllCellsMarked' function makes the dependencies of useEffect Hook (at line 73) change on every render. Move it inside the useEffect callback. Alternatively, wrap the definition of 'isAllCellsMarked' in its own useCallback() Hook    react-hooks/exhaustive-deps
  Line 48:11:  The 'addPlusOneVictory' function makes the dependencies of useEffect Hook (at line 73) change on every render. Move it inside the useEffect callback. Alternatively, wrap the definition of 'addPlusOneVictory' in its own useCallback() Hook  react-hooks/exhaustive-deps
  Line 54:11:  The 'refreshPlayCells' function makes the dependencies of useEffect Hook (at line 73) change on every render. Move it inside the useEffect callback. Alternatively, wrap the definition of 'refreshPlayCells' in its own useCallback() Hook    react-hooks/exhaustive-deps
  
  
  Мне оборачивать функции в useCallback()?

2021-03-25 12:05 UTC, yegorgangalo commented on src/App.js
> +  useEffect(() => {
Как видишь, реакт сам говорит засунуть оглашение функций обратно в useEffect

2021-03-25 12:10 UTC, EugeneSolovyev commented on src/App.js
> +  useEffect(() => {
то что он тебя просит вернуть их в useEffect - это не лучшее решение
здесь может быть проблема в том что на каждый чих у тебя ф-ии пересоздаются, поэтому он и говорит тебе о useCallback
что в целом не самое худшее решение (врапнуть useCallback-ом)

2021-03-25 12:11 UTC, EugeneSolovyev commented on src/components/Form/Form.js
> +    }
важно поработать со стороними либами для форм
самые распространненные formik и redux-form

2021-03-25 12:12 UTC, EugeneSolovyev commented on src/components/TurnToPlay/TurnToPlay.js
> +                <span className={s.turnToPlay}>{currentPlayer.name} </span>
это принципиально, переменные, названия ф-ий, импорты должны нести смысловую нагрузку, а `s` такого не делает

2021-03-25 12:12 UTC, EugeneSolovyev commented on src/index.js
> +      {/* <PersistGate loading={null} persistor={persistor}> */}
не забывай

2021-03-25 12:13 UTC, EugeneSolovyev commented on src/redux/playCells/playCells-reducer.js
> +const showCellsScreen = createReducer(false, {
тут сделаешь как я тебе показывал через принцип открытости-закрытости?

2021-03-25 12:14 UTC, yegorgangalo commented on src/redux/playCells/playCells-reducer.js
> +const showCellsScreen = createReducer(false, {
в процессе)

2021-03-25 13:35 UTC, yegorgangalo commented on src/App.js
> +  useEffect(() => {
Переделал. Использовал useCallback() и useMemo()

2021-03-25 15:36 UTC, yegorgangalo commented on src/redux/playCells/playCells-reducer.js
> +const showCellsScreen = createReducer(false, {
Сделал пока только для playersReducer.
Как по мне код стал менее декларативным. Код в екшенах плохо читается. Мне говорили, что чистый редакс мало сейчас используют. Все пишут через обертку редакс-тулкит или вообще редакс-сага.
И не понимаю зачем у тебя использовано каррирование  с передачей dispatch. Работает и без него:
export const setCurrentPlayer = (playerObj) => (dispatch) =>
  dispatch({
    type: 'PLAYER_TYPE',
    payload: (state) => ({
        ...state,
        currentPlayer: playerObj,
    })
  })

Я сделал так и работает:
export const setCurrentPlayer = (playerObj) =>
  ({
    type: 'PLAYER_TYPE',
    payload: (state) => ({
        ...state,
        currentPlayer: playerObj,
    })
  })
  
Или я не до конца понял твою технологию?)

2021-03-25 15:37 UTC, yegorgangalo commented on src/components/TurnToPlay/TurnToPlay.js
> +                <span className={s.turnToPlay}>{currentPlayer.name} </span>
Done!)

2021-03-25 15:37 UTC, yegorgangalo commented on src/components/Form/Form.js
> +    }
Позже сделаю на redux-form. С формиком имел дело, потому изучу новенькое)

2021-03-25 20:23 UTC, yegorgangalo commented on src/components/Form/Form.js
> +    }
на сайте https://redux-form.com/8.3.0/ написано:
"Attention: Do not begin a project with Redux Form. The author of Redux Form has written a superior library, React Final Form."
Юзать React Final Form?

2021-03-26 07:37 UTC, EugeneSolovyev requested changes

2021-03-26 07:37 UTC, EugeneSolovyev commented on src/App.js
> +  const winCombinations = useMemo(() => [
поскольку winCombinations по своей сути статичны, то ты спокойно можешь вынести эту константу за пределы компонента (естественно без использования useMemo :)

2021-03-26 07:37 UTC, EugeneSolovyev commented on src/App.js
> +      : dispatch(playersActions.increaseVictory1());
```js
const callback = currentPlayer.name === player1.name ? playersActions.increaseVictory2 : playersActions.increaseVictory1
dispatch(callback())
```
чутка упрости так, диспатч-то ты вызываешь в любом случае

2021-03-26 07:37 UTC, EugeneSolovyev commented on src/App.js
> +  }, [dispatch]);
тут думаю необязательно dispatch передавать как зависимость

2021-03-26 07:37 UTC, EugeneSolovyev commented on src/App.js
>      }
вот тут бы я сделал два разных useEffect-а
```js
// первый для count
useEffect(() => {
  if (count >= 9) refreshPlayCells();
}, [count])

// второй для проверки победителя
useEffect(() => {
  if (!isWinner(playCells)) return;
  addPlusOneVictory();
  refreshPlayCells();
}, [playCells])
```
при этом у тебя еще есть проверка на `count < 5`, её можно вынести в isWinner

2021-03-26 07:37 UTC, EugeneSolovyev commented on src/components/Form/Form.js
> +    }
угу, блин, я чет это мисанул
хорошо что нашел, молодец)

2021-03-26 07:37 UTC, EugeneSolovyev commented on src/redux/players/players-actions.js
> +//   })
закомменченный код

2021-03-26 07:37 UTC, EugeneSolovyev commented on src/redux/players/players-actions.js
> +// export const increaseVictory2 = createAction('player2/increaseVictory');
закомменченный код

2021-03-26 07:44 UTC, yegorgangalo commented on src/redux/players/players-actions.js
> +//   })
Не ругайся) Это я специально оставил, пока не разобрался с твоим методом до конца

2021-03-26 07:44 UTC, yegorgangalo commented on src/redux/players/players-actions.js
> +// export const increaseVictory2 = createAction('player2/increaseVictory');
Не ругайся) Это я специально оставил, пока не разобрался с твоим методом до конца

2021-03-26 07:59 UTC, yegorgangalo commented on src/App.js
>      }
Разбил на два useEffect-а.
а в чем плюс разбиения на два useEffect?
так вместо одной проверки происходит две.
И если вынести проверку на count < 5 во внутрь isWinner, тогда isWinner будет вызываться каждый раз, а я именно потому и использую count, чтоб первые четыре хода isWinner не вызывалась.

2021-03-26 08:00 UTC, yegorgangalo commented on src/App.js
> +  }, [dispatch]);
Это не моя прихоть)
так желает реакт)

2021-03-26 08:04 UTC, yegorgangalo commented on src/App.js
> +      : dispatch(playersActions.increaseVictory1());
done

2021-03-26 08:58 UTC, yegorgangalo commented on src/redux/playCells/playCells-reducer.js
> +const showCellsScreen = createReducer(false, {
чтоб редакс не матюкался на несериализируемые данные в экшенах, добавил тип экшена 'PLAYER_TYPE' в исключение.
Это правильное решение?
const middleware = [
  ...getDefaultMiddleware({
    serializableCheck: {
      ignoredActions: [FLUSH, REHYDRATE, PAUSE, PERSIST, PURGE, REGISTER, 'PLAYER_TYPE'],
    },
  }),
];

2021-03-26 09:01 UTC, yegorgangalo commented on src/App.js
> +  const winCombinations = useMemo(() => [
Круть! Он ведь тогда не будет каждый раз пересоздаваться при ререндере (а точнее useMemo не будет каждый раз запускаться). Как я сам не догадался?)

2021-03-26 09:12 UTC, yegorgangalo commented on src/App.js
> +  const winCombinations = useMemo(() => [
Кстати, а стоить точно также вынести функции isWinner, addPlusOneVictory, refreshPlayCells тоже вне компонента, чтобы не юзать useCallback?
Ведь  useCallback также каждый раз вызывается при ререндере для проверки изменений параметров функции, что тоже есть лишняя операция.

2021-03-29 11:50 UTC, merged